databases:
  - name: assignment-db
    databaseName: assignment_system
    user: assignment_user

services:
  # User Service Backend
  - type: web
    name: user-service
    env: docker
    dockerfilePath: ./backend/user-service/Dockerfile
    dockerContext: ./backend/user-service
    envVars:
      - key: JAVA_VERSION
        value: 21
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: assignment-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: assignment-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: assignment-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 3600000
      - key: CORS_ALLOWED_ORIGINS
        sync: false

  # Submission Service Backend
  - type: web
    name: submission-service
    env: docker
    dockerfilePath: ./backend/submission-service/Dockerfile
    dockerContext: ./backend/submission-service
    envVars:
      - key: JAVA_VERSION
        value: 21
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: assignment-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: assignment-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: assignment-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 3600000
      - key: FILE_UPLOAD_DIR
        value: /opt/render/project/uploads
      - key: CORS_ALLOWED_ORIGINS
        sync: false

  # Frontend Static Site
  - type: web
    name: assignment-frontend
    env: static
    buildCommand: pnpm install && pnpm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: VITE_API_USER_URL
        sync: false
      - key: VITE_API_SUBMISSION_URL
        sync: false
